package configparse;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class ConfigParseJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfigParseJFrame
     */
    public ConfigParseJFrame() {
        FileProcessor.loadSetting("./setting.properties");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        funcbuttonGroup = new javax.swing.ButtonGroup();
        jLayeredPane = new javax.swing.JLayeredPane();
        funjPanel = new javax.swing.JPanel();
        totemjRadioButton = new javax.swing.JRadioButton();
        upgradeBuildingjRadioButton = new javax.swing.JRadioButton();
        bigPackjRadioButton = new javax.swing.JRadioButton();
        exchangejRadioButton = new javax.swing.JRadioButton();
        tigerItemInfojRadioButton = new javax.swing.JRadioButton();
        flowerlandSpinjRadioButton = new javax.swing.JRadioButton();
        keyMappingjRadioButton = new javax.swing.JRadioButton();
        adsGeneralizejRadioButton = new javax.swing.JRadioButton();
        fsGeneralizejRadioButton = new javax.swing.JRadioButton();
        sapphireExchangejRadioButton = new javax.swing.JRadioButton();
        flowerCraftjRadioButton = new javax.swing.JRadioButton();
        floralBenchUpgradejRadioButton = new javax.swing.JRadioButton();
        unockFlowerCraftjRadioButton = new javax.swing.JRadioButton();
        floralBenchGroupjRadioButton = new javax.swing.JRadioButton();
        floralBenchGroupMakeListjRadioButton = new javax.swing.JRadioButton();
        gardenExpandjRadioButton = new javax.swing.JRadioButton();
        itemExtendjRadioButton = new javax.swing.JRadioButton();
        slotInfojRadioButton = new javax.swing.JRadioButton();
        divinationInfojRadioButton = new javax.swing.JRadioButton();
        divinationExchangeInfojRadioButton = new javax.swing.JRadioButton();
        virtualCurrencyjRadioButton = new javax.swing.JRadioButton();
        divinationCommonInfojRadioButton = new javax.swing.JRadioButton();
        selectConfgFilejPanel = new javax.swing.JPanel();
        configFilejLabel = new javax.swing.JLabel();
        configFilejTextField = new javax.swing.JTextField();
        configFilejButton = new javax.swing.JButton();
        outputjLabel = new javax.swing.JLabel();
        outputjTextField = new javax.swing.JTextField();
        outputjButton = new javax.swing.JButton();
        operationjPanel = new javax.swing.JPanel();
        parsejButton = new javax.swing.JButton();
        closejButton = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        filejMenu = new javax.swing.JMenu();
        settingjMenuItem = new javax.swing.JMenuItem();
        editjMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        funjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("解析内容"));

        funcbuttonGroup.add(totemjRadioButton);
        totemjRadioButton.setText("图腾配置文件");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, funcbuttonGroup, org.jdesktop.beansbinding.ELProperty.create("TOTEM"), totemjRadioButton, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        totemjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totemjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(upgradeBuildingjRadioButton);
        upgradeBuildingjRadioButton.setText("建筑升级");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, funcbuttonGroup, org.jdesktop.beansbinding.ELProperty.create("UPGRADE_BUILDING"), upgradeBuildingjRadioButton, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        upgradeBuildingjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeBuildingjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(bigPackjRadioButton);
        bigPackjRadioButton.setText("大礼包");
        bigPackjRadioButton.setActionCommand("BIGPACK");
        bigPackjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bigPackjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(exchangejRadioButton);
        exchangejRadioButton.setText("兑换任务");
        exchangejRadioButton.setActionCommand("EXCHANGE");
        exchangejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exchangejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(tigerItemInfojRadioButton);
        tigerItemInfojRadioButton.setText("实验室种子机");
        tigerItemInfojRadioButton.setActionCommand("TIGERITEMINFO");
        tigerItemInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tigerItemInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(flowerlandSpinjRadioButton);
        flowerlandSpinjRadioButton.setText("游乐场老虎机");
        flowerlandSpinjRadioButton.setActionCommand("FLOWERLAND_SPIN");
        flowerlandSpinjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flowerlandSpinjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(keyMappingjRadioButton);
        keyMappingjRadioButton.setText("关键字映射");
        keyMappingjRadioButton.setActionCommand("KEYMAPPING");
        keyMappingjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyMappingjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(adsGeneralizejRadioButton);
        adsGeneralizejRadioButton.setText("小语种广告推广");
        adsGeneralizejRadioButton.setActionCommand("ADSGENERALIZE");
        adsGeneralizejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adsGeneralizejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(fsGeneralizejRadioButton);
        fsGeneralizejRadioButton.setText("小语种花店推广");
        fsGeneralizejRadioButton.setActionCommand("FSGENERALIZE");
        fsGeneralizejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fsGeneralizejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(sapphireExchangejRadioButton);
        sapphireExchangejRadioButton.setText("宝石兑换");
        sapphireExchangejRadioButton.setActionCommand("SAPPHIREEXCHANGE");
        sapphireExchangejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sapphireExchangejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(flowerCraftjRadioButton);
        flowerCraftjRadioButton.setText("花艺品");
        flowerCraftjRadioButton.setActionCommand("FLOWERCRAFT");
        flowerCraftjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flowerCraftjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(floralBenchUpgradejRadioButton);
        floralBenchUpgradejRadioButton.setText("花艺制作台升级");
        floralBenchUpgradejRadioButton.setActionCommand("FLORALBENCHUPRADE");
        floralBenchUpgradejRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floralBenchUpgradejRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(unockFlowerCraftjRadioButton);
        unockFlowerCraftjRadioButton.setText("花艺解锁");
        unockFlowerCraftjRadioButton.setActionCommand("UNLOCKFLOWERCRAFT");
        unockFlowerCraftjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unockFlowerCraftjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(floralBenchGroupjRadioButton);
        floralBenchGroupjRadioButton.setText("花艺制作台分组");
        floralBenchGroupjRadioButton.setActionCommand("FLORALBENCHGROUP");
        floralBenchGroupjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floralBenchGroupjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(floralBenchGroupMakeListjRadioButton);
        floralBenchGroupMakeListjRadioButton.setText("制作台制作清单");
        floralBenchGroupMakeListjRadioButton.setActionCommand("FLORALBENCHMAKELIST");
        floralBenchGroupMakeListjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floralBenchGroupMakeListjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(gardenExpandjRadioButton);
        gardenExpandjRadioButton.setText("后花园扩地");
        gardenExpandjRadioButton.setActionCommand("GARDENEXPAND");
        gardenExpandjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gardenExpandjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(itemExtendjRadioButton);
        itemExtendjRadioButton.setText("物品扩展");
        itemExtendjRadioButton.setActionCommand("ITEMEXTEND");
        itemExtendjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemExtendjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(slotInfojRadioButton);
        slotInfojRadioButton.setText("拉霸");
        slotInfojRadioButton.setActionCommand("SLOTINFO");
        slotInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(divinationInfojRadioButton);
        divinationInfojRadioButton.setText("占卜塔罗牌");
        divinationInfojRadioButton.setActionCommand("DIVINATION_INFO");
        divinationInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divinationInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(divinationExchangeInfojRadioButton);
        divinationExchangeInfojRadioButton.setText("占卜兑换");
        divinationExchangeInfojRadioButton.setActionCommand("DIVINATION_EXCHANGE_INFO");
        divinationExchangeInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divinationExchangeInfojRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(virtualCurrencyjRadioButton);
        virtualCurrencyjRadioButton.setText("虚拟货币");
        virtualCurrencyjRadioButton.setActionCommand("VIRTUAL_CURRENCY");
        virtualCurrencyjRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                virtualCurrencyjRadioButtonMouseClicked(evt);
            }
        });

        funcbuttonGroup.add(divinationCommonInfojRadioButton);
        divinationCommonInfojRadioButton.setText("占卜通用信息");
        divinationCommonInfojRadioButton.setActionCommand("DIVINATION_COMMON_INFO");
        divinationCommonInfojRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divinationCommonInfojRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout funjPanelLayout = new javax.swing.GroupLayout(funjPanel);
        funjPanel.setLayout(funjPanelLayout);
        funjPanelLayout.setHorizontalGroup(
            funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funjPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totemjRadioButton)
                    .addComponent(exchangejRadioButton)
                    .addComponent(keyMappingjRadioButton)
                    .addComponent(sapphireExchangejRadioButton)
                    .addComponent(unockFlowerCraftjRadioButton)
                    .addComponent(gardenExpandjRadioButton)
                    .addComponent(divinationExchangeInfojRadioButton)
                    .addComponent(virtualCurrencyjRadioButton))
                .addGap(18, 18, 18)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funjPanelLayout.createSequentialGroup()
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upgradeBuildingjRadioButton)
                            .addComponent(tigerItemInfojRadioButton)
                            .addComponent(adsGeneralizejRadioButton)
                            .addComponent(flowerCraftjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floralBenchUpgradejRadioButton)
                            .addComponent(fsGeneralizejRadioButton)
                            .addComponent(flowerlandSpinjRadioButton)
                            .addComponent(bigPackjRadioButton)))
                    .addGroup(funjPanelLayout.createSequentialGroup()
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floralBenchGroupjRadioButton)
                            .addComponent(divinationInfojRadioButton)
                            .addComponent(slotInfojRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divinationCommonInfojRadioButton)
                            .addComponent(itemExtendjRadioButton)
                            .addComponent(floralBenchGroupMakeListjRadioButton))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        funjPanelLayout.setVerticalGroup(
            funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funjPanelLayout.createSequentialGroup()
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totemjRadioButton)
                    .addComponent(upgradeBuildingjRadioButton)
                    .addComponent(bigPackjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exchangejRadioButton)
                    .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tigerItemInfojRadioButton)
                        .addComponent(flowerlandSpinjRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyMappingjRadioButton)
                    .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adsGeneralizejRadioButton)
                        .addComponent(fsGeneralizejRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sapphireExchangejRadioButton)
                    .addComponent(flowerCraftjRadioButton)
                    .addComponent(floralBenchUpgradejRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(floralBenchGroupjRadioButton)
                        .addComponent(floralBenchGroupMakeListjRadioButton))
                    .addComponent(unockFlowerCraftjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funjPanelLayout.createSequentialGroup()
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slotInfojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemExtendjRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(funjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divinationInfojRadioButton)
                            .addComponent(divinationCommonInfojRadioButton)))
                    .addGroup(funjPanelLayout.createSequentialGroup()
                        .addComponent(gardenExpandjRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divinationExchangeInfojRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(virtualCurrencyjRadioButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        funjPanel.setBounds(10, 0, 390, 250);
        jLayeredPane.add(funjPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        selectConfgFilejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("选择配置文件"));

        configFilejLabel.setText("配置文件：");

        configFilejTextField.setText(FileProcessor.configBaseDir);
        configFilejTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configFilejTextFieldMouseClicked(evt);
            }
        });

        configFilejButton.setText("浏览");
        configFilejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configFilejButtonMouseClicked(evt);
            }
        });

        outputjLabel.setText("输出目录：");

        outputjTextField.setText(FileProcessor.outputDirectory);
        outputjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputjTextFieldMouseClicked(evt);
            }
        });

        outputjButton.setText("浏览");
        outputjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outputjButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout selectConfgFilejPanelLayout = new javax.swing.GroupLayout(selectConfgFilejPanel);
        selectConfgFilejPanel.setLayout(selectConfgFilejPanelLayout);
        selectConfgFilejPanelLayout.setHorizontalGroup(
            selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectConfgFilejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputjLabel)
                    .addComponent(configFilejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(configFilejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(configFilejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        selectConfgFilejPanelLayout.setVerticalGroup(
            selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectConfgFilejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configFilejLabel)
                    .addComponent(configFilejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configFilejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectConfgFilejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputjLabel)
                    .addComponent(outputjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectConfgFilejPanel.setBounds(10, 250, 390, 98);
        jLayeredPane.add(selectConfgFilejPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        operationjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("操作"));

        parsejButton.setText("解析");
        parsejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parsejButtonMouseClicked(evt);
            }
        });

        closejButton.setText("取消");
        closejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closejButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout operationjPanelLayout = new javax.swing.GroupLayout(operationjPanel);
        operationjPanel.setLayout(operationjPanelLayout);
        operationjPanelLayout.setHorizontalGroup(
            operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationjPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(parsejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        operationjPanelLayout.setVerticalGroup(
            operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parsejButton)
                    .addComponent(closejButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filejMenu.setText("文件");

        settingjMenuItem.setText("设置");
        settingjMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingjMenuItemMouseClicked(evt);
            }
        });
        filejMenu.add(settingjMenuItem);

        jMenuBar.add(filejMenu);

        editjMenu.setText("编辑");
        jMenuBar.add(editjMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(operationjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(operationjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configFilejTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configFilejTextFieldMouseClicked
        File f = new File(FileProcessor.configBaseDir);
        JFileChooser jfc = new JFileChooser(f);
        int result;
        result = jfc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            configFilejTextField.setText(file.getPath());
        }
    }//GEN-LAST:event_configFilejTextFieldMouseClicked

    private void configFilejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configFilejButtonMouseClicked
        this.configFilejTextFieldMouseClicked(evt);
    }//GEN-LAST:event_configFilejButtonMouseClicked

    private void outputjTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputjTextFieldMouseClicked
        File f = new File(FileProcessor.outputDirectory);
        JFileChooser jfc = new JFileChooser(f);
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result;
        result = jfc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            outputjTextField.setText(file.getPath());
        }
    }//GEN-LAST:event_outputjTextFieldMouseClicked

    private void outputjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputjButtonMouseClicked
        this.outputjTextFieldMouseClicked(evt);
    }//GEN-LAST:event_outputjButtonMouseClicked

    private void parsejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parsejButtonMouseClicked
        //功能选择
        String func = "";
        if (funcbuttonGroup.getSelection() != null) {
            func = funcbuttonGroup.getSelection().getActionCommand();
        }
        //配置文件
        String configFilePath = configFilejTextField.getText();
        //输出路径
        String outputPath = outputjTextField.getText();

        String msg = "";
        if (func.isEmpty()) {
            msg = "请选择解析内容 ";
        } else if (configFilePath.isEmpty()) {
            msg = "请选择待解析文件(xls) ";
        } else if (outputPath.isEmpty()) {
            msg = "请选择输出路径";
        }
        if (!msg.isEmpty()) {
            JOptionPane.showMessageDialog(null, msg, "信息提示", JOptionPane.ERROR_MESSAGE);
        } else {
            if ("UPGRADE_BUILDING".equals(func)) {//建筑升级相关配置
                DataParse.transformUpgradeBuildingConfig(configFilePath, func, outputPath);
            }
            JOptionPane.showMessageDialog(null, "转换结束");
            this.dispose();
//            int dialogResult = JOptionPane.showConfirmDialog(null, "转换成功,继续转换其他配置项？", "转换结果提示", JOptionPane.YES_NO_OPTION);
//            if (JOptionPane.NO_OPTION == dialogResult) {
//                this.dispose();
//            }
        }
    }//GEN-LAST:event_parsejButtonMouseClicked

    private void closejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closejButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_closejButtonMouseClicked

    private void settingjMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingjMenuItemMouseClicked
    }//GEN-LAST:event_settingjMenuItemMouseClicked

    private void totemjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totemjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_totemjRadioButtonMouseClicked

    private void upgradeBuildingjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeBuildingjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_upgradeBuildingjRadioButtonMouseClicked

    private void bigPackjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigPackjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_bigPackjRadioButtonMouseClicked

    private void exchangejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exchangejRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_exchangejRadioButtonMouseClicked

    private void tigerItemInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tigerItemInfojRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_tigerItemInfojRadioButtonMouseClicked

    private void flowerlandSpinjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerlandSpinjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_flowerlandSpinjRadioButtonMouseClicked

    private void keyMappingjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyMappingjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_keyMappingjRadioButtonMouseClicked

    private void adsGeneralizejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adsGeneralizejRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_adsGeneralizejRadioButtonMouseClicked

    private void fsGeneralizejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsGeneralizejRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_fsGeneralizejRadioButtonMouseClicked

    private void sapphireExchangejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapphireExchangejRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_sapphireExchangejRadioButtonMouseClicked

    private void flowerCraftjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flowerCraftjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_flowerCraftjRadioButtonMouseClicked

    private void floralBenchUpgradejRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floralBenchUpgradejRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_floralBenchUpgradejRadioButtonMouseClicked

    private void unockFlowerCraftjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unockFlowerCraftjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_unockFlowerCraftjRadioButtonMouseClicked

    private void floralBenchGroupjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floralBenchGroupjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_floralBenchGroupjRadioButtonMouseClicked

    private void floralBenchGroupMakeListjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floralBenchGroupMakeListjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_floralBenchGroupMakeListjRadioButtonMouseClicked

    private void gardenExpandjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gardenExpandjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_gardenExpandjRadioButtonMouseClicked

    private void itemExtendjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemExtendjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_itemExtendjRadioButtonMouseClicked

    private void slotInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotInfojRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_slotInfojRadioButtonMouseClicked

    private void divinationInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divinationInfojRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_divinationInfojRadioButtonMouseClicked

    private void divinationExchangeInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divinationExchangeInfojRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_divinationExchangeInfojRadioButtonMouseClicked

    private void virtualCurrencyjRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_virtualCurrencyjRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_virtualCurrencyjRadioButtonMouseClicked

    private void divinationCommonInfojRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divinationCommonInfojRadioButtonMouseClicked
        ChangeConfigFilejTextField();
    }//GEN-LAST:event_divinationCommonInfojRadioButtonMouseClicked

    private void ChangeConfigFilejTextField() {
        String key;
        if (funcbuttonGroup.getSelection() != null) {
            key = funcbuttonGroup.getSelection().getActionCommand();
            configFilejTextField.setText(FileProcessor.configBaseDir + "/" + FileProcessor.fileMapping.get(key));
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        FileProcessor.initFileMapping();//初始化 对应关系

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigParseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            FileProcessor.showMessageDialogMessage(ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigParseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            FileProcessor.showMessageDialogMessage(ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigParseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            FileProcessor.showMessageDialogMessage(ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigParseJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            FileProcessor.showMessageDialogMessage(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ConfigParseJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ConfigParseJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ConfigParseJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ConfigParseJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                JFrame totemCfgFrame = new ConfigParseJFrame();
                totemCfgFrame.setLocationRelativeTo(null);
                totemCfgFrame.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adsGeneralizejRadioButton;
    private javax.swing.JRadioButton bigPackjRadioButton;
    private javax.swing.JButton closejButton;
    private javax.swing.JButton configFilejButton;
    private javax.swing.JLabel configFilejLabel;
    private javax.swing.JTextField configFilejTextField;
    private javax.swing.JRadioButton divinationCommonInfojRadioButton;
    private javax.swing.JRadioButton divinationExchangeInfojRadioButton;
    private javax.swing.JRadioButton divinationInfojRadioButton;
    private javax.swing.JMenu editjMenu;
    private javax.swing.JRadioButton exchangejRadioButton;
    private javax.swing.JMenu filejMenu;
    private javax.swing.JRadioButton floralBenchGroupMakeListjRadioButton;
    private javax.swing.JRadioButton floralBenchGroupjRadioButton;
    private javax.swing.JRadioButton floralBenchUpgradejRadioButton;
    private javax.swing.JRadioButton flowerCraftjRadioButton;
    private javax.swing.JRadioButton flowerlandSpinjRadioButton;
    private javax.swing.JRadioButton fsGeneralizejRadioButton;
    private javax.swing.ButtonGroup funcbuttonGroup;
    private javax.swing.JPanel funjPanel;
    private javax.swing.JRadioButton gardenExpandjRadioButton;
    private javax.swing.JRadioButton itemExtendjRadioButton;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JRadioButton keyMappingjRadioButton;
    private javax.swing.JPanel operationjPanel;
    private javax.swing.JButton outputjButton;
    private javax.swing.JLabel outputjLabel;
    private javax.swing.JTextField outputjTextField;
    private javax.swing.JButton parsejButton;
    private javax.swing.JRadioButton sapphireExchangejRadioButton;
    private javax.swing.JPanel selectConfgFilejPanel;
    private javax.swing.JMenuItem settingjMenuItem;
    private javax.swing.JRadioButton slotInfojRadioButton;
    private javax.swing.JRadioButton tigerItemInfojRadioButton;
    private javax.swing.JRadioButton totemjRadioButton;
    private javax.swing.JRadioButton unockFlowerCraftjRadioButton;
    private javax.swing.JRadioButton upgradeBuildingjRadioButton;
    private javax.swing.JRadioButton virtualCurrencyjRadioButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
